### ISSUE TITLE
Pictures with transparency

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [geoffm39/watermarking-app#1]
It is not very friendly to png format images with transparent parts of the code. The transparent parts will be colored.

**Comment by geoffm39** [comment]
Thank you for your contribution and feedback.
Sorry for the late reply, I have been on holidays.

I have made changes to the `save_images()` method to keep the original mode of each image.
If this was not the issue you were referring could you kindly provide any additional details so I can resolve the issue.

Thank you for your time,
Geoff

**Comment by Jeck-Liu-Create** [comment]
Thank you for your modification, it can solve the problem I encountered.
